### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by adocampo** [zuoez02/siyuan-plugin-whiteboard#14]
Hello, 

I'm using Siyuan since a few days, I'm very impressed, but I just miss a hand writting note feature, so tldraw integration is exactly what I was looking for, I love it! Awesome work!

There are a lot of chinese labels, though, and yet many of them are deductible by context, it would be nice to have it in other languages. I can offer to translate them into spanish if there is any label in english, or I could even use some online translator to translate from chinese to english, but as far as I saw, labels are hardcoded into the source, not in the i18n directory.

Is there any plan to translate the plugin?

Thank you very much for your work!!

**Comment by zuoez02** [comment]
Support in next version

**Comment by adocampo** [comment]
perfect! let me know here if you need some help translating into spanish (I speak natively catalan as well, but siyuan isn't in catalan, so I think your plugin doesn't need to be translated into catalan either)

**Comment by zuoez02** [comment]
Tldraw has already have translation, you can choose language at bottom right corner button.
![image](https://github.com/zuoez02/siyuan-plugin-whiteboard/assets/4801955/9140db03-347d-4fa6-bfca-9f8c9a0f2925)

I will translate other function text in English, then you can translate it to your languange which must supported by Siyuan.
![image](https://github.com/zuoez02/siyuan-plugin-whiteboard/assets/4801955/67950ad6-c2c0-4302-bc95-cd82373f198b)

**Comment by adocampo** [comment]
yes, I didn't explain myself properly, I wasn't speaking about tldraw, but tldraw _plugin for siyuan_. Which is in Chinese is not tldraw interface, but the siyuan modal forms, tooltips, etc, of this plugin
![image](https://github.com/zuoez02/siyuan-plugin-whiteboard/assets/2266612/84959625-6b04-4b9b-9f67-81f8ebb0d7cd)
![image](https://github.com/zuoez02/siyuan-plugin-whiteboard/assets/2266612/daad5384-459f-4141-a6e8-31a89215909a)
![image](https://github.com/zuoez02/siyuan-plugin-whiteboard/assets/2266612/206b2a35-5070-442a-9027-38bcd65a1c84)
![image](https://github.com/zuoez02/siyuan-plugin-whiteboard/assets/2266612/a086ef59-9f52-4f11-8d24-86fb93e1f616)

**Comment by zuoez02** [comment]
I have add en_US support in v0.1.8, and I tried to translate it in es_ES with GPT. You can create PR if the translation is mistake :). The file is in README_es_ES.md and src/i18n/es_ES.json

**Comment by adocampo** [comment]
Hi there!
The translation both in english and spanish are quite good, so far. The only thin I should change should be this tooltip
![image](https://github.com/zuoez02/siyuan-plugin-whiteboard/assets/2266612/efe87fee-d947-4036-800d-87fcd9195e54)

It should be "Minimize" in english and "Minimizar" in spanish.

**Comment by zuoez02** [comment]
> Hi there! The translation both in english and spanish are quite good, so far. The only thin I should change should be this tooltip ![image](https://private-user-images.githubusercontent.com/2266612/300412736-efe87fee-d947-4036-800d-87fcd9195e54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MzQwNDEsIm5iZiI6MTcwNjUzMzc0MSwicGF0aCI6Ii8yMjY2NjEyLzMwMDQxMjczNi1lZmU4N2ZlZS1kOTQ3LTQwMzYtODAwZC04N2ZjZDkxOTVlNTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjlUMTMwOTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDViYWYxZjJiNTFjMGUzYzI2MTMxZmY0MDg5NDRjZTJlMzhjYWI0NTBiNTRlYzhlNTJkYjk4NDVlNDZhZjcwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4xWstitvIp83NtyaFA8OJbmzQ4ajLmXZUWyKGUcdr58)
> 
> It should be "Minimize" in english and "Minimizar" in spanish.

Fixed in v0.1.10

**Comment by adocampo** [comment]
I've found another text in chinese. This time inside the tldraw board, so I'm not sure this is related to this plugin.
If I copy a block of a normal note, and paste it on the whiteboard, it shows this
![image](https://github.com/zuoez02/siyuan-plugin-whiteboard/assets/2266612/ca3d7474-a778-46e8-8d20-04afc93df243)

If I click on that button with the chinese text, it opens the document, so by deduction, it must say something like "open link"
