### ISSUE TITLE
挂件和移动端同步的想法

### ISSUE THREAD

**Issue by UICO32** [zuoez02/siyuan-plugin-whiteboard#4]
两个想法：
- 能否做成挂件，类似excalidraw的挂件。这样的好处是可以插入到页首，便于直观管理项目（鉴于目前已经可以预览嵌入块）
- 能否实现和移动端的同步。tldraw的一个巨大优势在于移动端交互非常丝滑，手写体验也不错，如果能够同步可以一定程度解决碎片化记录的问题。
总之，非常感谢作者开发这个插件！

**Comment by zuoez02** [comment]
第一点可以考虑。第二点目前思源移动端很弱，需要促进思源移动端进步才有机会
